CREATE TABLE BOOKS (
  ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL,
  BOOK_LANGUAGE VARCHAR(255) NOT NULL,
  PUBLISH_YEAR INT NOT NULL,
  GENRE VARCHAR(255) NULL,
  ISBN VARCHAR(255) NOT NULL,
  PRICE DOUBLE NOT NULL,
  PAGES INT NOT NULL,
  ANNOTATION VARCHAR(100) NULL,
  RATING INT NULL,
  IS_NEW BOOLEAN NOT NULL,
  AMOUNT INT NOT NULL,
  COVER INT NULL
);

INSERT INTO BOOKS (NAME, AUTHOR, BOOK_LANGUAGE, PUBLISH_YEAR, GENRE, ISBN, PRICE, PAGES, ANNOTATION, RATING, IS_NEW, AMOUNT, COVER)
VALUES (
  '1984',
  'Джордж Оруэлл',
  'Английский',
  2023,
  'Антиутопия',
  '978-5-04-113136-7',
  350,
  328,
  'Классическая антиутопия о тоталитарном обществе будущего, где свобода слова и мысли подавлена.',
  8,
  true,
  2,
  2
);

INSERT INTO BOOKS (NAME, AUTHOR, BOOK_LANGUAGE, PUBLISH_YEAR, GENRE, ISBN, PRICE, PAGES, ANNOTATION, RATING, IS_NEW, AMOUNT, COVER)
VALUES (
  'Мастер и Маргарита',
  'Михаил Булгаков',
  'Русский',
  2021,
  'Роман',
  '978-5-04-094927-5',
  400,
  432,
  'Философский роман о противостоянии добра и зла в Москве 1930-х годов.',
  9,
  true,
  4,
  2
);


